version: '3.4'

services:
  python_course:
    image: python_course
    build:
      context: ./python_course
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 5000"]
    ports:
      - 5000:5000
      - 5678:5678
    environment:
      - FLASK_APP=python_course/draft_order_generator.py
